# pages/Filter_Universal_By_GoodTickers.py
import io
from pathlib import Path
from typing import List

import pandas as pd
import streamlit as st

st.set_page_config(page_title="Filter Universal by OK tickers", layout="wide")
st.title("Filter universal_portfolio_backup.csv using Probe good_tickers")

st.markdown(
    """
Use this temporary page to produce a filtered universal_portfolio_backup CSV
containing only the tickers that the Probe page marked OK. After downloading
the filtered CSV, upload it back via the Universal Portfolio → Restore UI
(choose Replace) and then re-run the optimizer dry-run.
"""
)

# Helpers
def normalize_ticker(s: str) -> str:
    if s is None:
        return ""
    t = str(s).strip()
    if not t:
        return ""
    # remove common invisible characters
    t = t.replace("\ufeff", "").replace("\u200b", "")
    return t.upper()

@st.cache_data(show_spinner=False)
def read_repo_universal(path: str = "universal_portfolio_backup.csv") -> pd.DataFrame:
    p = Path(path)
    if not p.exists():
        return pd.DataFrame()
    return pd.read_csv(p, dtype=str)

def read_uploaded_csv(uploaded) -> pd.DataFrame:
    try:
        return pd.read_csv(uploaded, dtype=str)
    except Exception:
        # fallback to lines
        uploaded.seek(0)
        text = uploaded.read().decode("utf-8-sig")
        lines = [l.strip() for l in text.splitlines() if l.strip()]
        return pd.DataFrame({"Ticker": lines})

# UI: load universal CSV
st.header("Step 1 — Source universal_portfolio_backup CSV")
repo_df = read_repo_universal()
use_repo = False
uploaded_uni = None
if not repo_df.empty:
    st.success("Found universal_portfolio_backup.csv in the repo.")
    st.write(f"Rows in repo universal file: {len(repo_df):,}")
    use_repo = st.checkbox("Use the repository universal_portfolio_backup.csv", value=True)
if not use_repo:
    uploaded_uni = st.file_uploader("Or upload your universal_portfolio_backup CSV", type=["csv"], key="upload_uni")
    if uploaded_uni:
        repo_df = read_uploaded_csv(uploaded_uni)
        st.write(f"Rows in uploaded universal file: {len(repo_df):,}")

if repo_df.empty:
    st.info("No universal portfolio CSV found yet. Upload or add universal_portfolio_backup.csv to the repo.")
    st.stop()

st.markdown("Preview (first 20 rows):")
st.dataframe(repo_df.head(20), use_container_width=True)

# UI: load good tickers
st.header("Step 2 — Provide good_tickers (from Probe)")
uploaded_good = st.file_uploader("Upload good_tickers.csv (generated by Probe) or paste", type=["csv"], key="upload_good")
pasted = st.text_area("Or paste good tickers (one per line)", height=200, key="paste_good")

good_list: List[str] = []
if uploaded_good:
    try:
        good_df = pd.read_csv(uploaded_good, dtype=str)
        # common col names
        col = None
        for candidate in ("Ticker", "Yahoo Ticker", "Yahoo_Ticker", "ticker", "yahoo_ticker", "symbol", "Symbol"):
            if candidate in good_df.columns:
                col = candidate
                break
        if col is None:
            # fallback first column
            col = good_df.columns[0]
        good_list = good_df[col].dropna().astype(str).str.strip().map(normalize_ticker).tolist()
    except Exception:
        st.error("Could not read uploaded good_tickers.csv — ensure it's a simple CSV with one column of tickers.")
if not good_list and pasted and pasted.strip():
    lines = [l.strip() for l in pasted.splitlines() if l.strip()]
    good_list = [normalize_ticker(l) for l in lines]

if not good_list:
    st.warning("Provide good_tickers via upload or paste to proceed.")
    st.stop()

st.write(f"Good tickers count: {len(good_list):,}")

# Step 3: Determine which column to match on in the universal CSV
# Prefer 'Yahoo Ticker' column; fallback to 'Yahoo_Ticker', 'Ticker', 'Symbol', or first column.
col_candidates = ["Yahoo Ticker", "Yahoo_Ticker", "YahooTicker", "Ticker", "Symbol", "symbol"]
match_col = None
for c in col_candidates:
    if c in repo_df.columns:
        match_col = c
        break
if match_col is None:
    # fallback to first column
    match_col = repo_df.columns[0]
    st.info(f"No common column detected; using first column: {match_col}")

st.write(f"Matching on column: `{match_col}`")

# Normalize the universal df's match column and filter
uni = repo_df.copy()
uni[match_col] = uni[match_col].fillna("").astype(str).map(normalize_ticker)

# Perform filtering: keep rows whose normalized match value is in good_list
good_set = set(good_list)
filtered = uni[uni[match_col].isin(good_set)].copy()

st.header("Results")
st.write(f"Original rows: {len(repo_df):,} — Filtered rows: {len(filtered):,}")

if filtered.empty:
    st.error("Filtering produced zero rows. Check your good_tickers list and the matching column.")
    st.stop()

st.markdown("Preview filtered rows (first 50):")
st.dataframe(filtered.head(50), use_container_width=True)

# Allow download
buf = io.StringIO()
filtered.to_csv(buf, index=False, encoding="utf-8-sig")
csv_bytes = buf.getvalue().encode("utf-8-sig")

st.download_button(
    "Download filtered universal_portfolio_backup_filtered.csv",
    data=csv_bytes,
    file_name="universal_portfolio_backup_filtered.csv",
    mime="text/csv",
)

st.markdown(
    """
Next steps:
1. Download the filtered CSV above.
2. In the app's Universal Portfolio panel, upload the filtered CSV and choose **Replace universal portfolio**.
3. Return to the CSV-run page and rebuild the frozen input, then run the dry-run optimizer.
4. Download the analysis JSON and share it here if you want me to parse the results.
"""
)
